#!/usr/bin/env bash
#installs nginx server
apt-get -y update
apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
echo 'Hello World!' > /var/www/html/index.html
sudo schow -R root:root /var/www/html
sudo service nginx restart
