#!/usr/bin/env bash
# install nginx
apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/hmtl/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
