#!/usr/bin/env bash

# Install Nginx
apt-get -y update
apt-get -y install nginx

# Set up the default Nginx configuration with a basic "Hello World!" response
echo 'Hello World!' > /var/www/html/index.html
chown -R root:root /var/www/html
service nginx restart

# Configure redirection
echo "server {
	listen 80;

	server_name localhost;

	location /redirect_me {
		return 301 http://youtube.com/;
    	}

    	location / {
        	root /var/www/html;
        	index index.html index.htm;
    	}
}" | tee /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Display success message
echo "Nginx configured for redirection. Access http://localhost/redirect_me to test the redirection."
