#!/usr/bin/env bash
#this script automates the installation of the load balancer
#server(nginx server)
#removal of the current nginx server if it exists
com="nginx"
if command -v "$com"; then
	sudo apt-get -y remove nginx nginx-common
	sudo apt-get -y purge nginx nginx-common nginx-core
	sudo apt-get autoremove
fi
#installation of the nginx server
sudo apt-get -y update
sudo apt-get install nginx
sudo service ufw start
sudo ufw allow ssh
sudo ufw allow "Ngix HTTP"
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
#addition of the response to the header
search='server_name _;'
reply="a \\\\\\\\ add_header X-served-By \$hostname;"
sudo sed -i "/$search/$reply" /etc/nginx/sites-available/default
#redirections
reply="a \ \ \ \ \ \ \ \ location /redirect_me {return 301 https://youtube.com;}"
sudo sed -i "/$search/$reply" /etc/nginx/sites-available/default
#creation of redirection configuration
reply="a \ \ \ \ \ \ \ \ error_page 404 /404.html;"
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo service nginx restart
