#!/usr/bin/env bash
# executes fizzbuzz
for a in {1..100}; do
	fizz=$((a % 3))
	buzz=$((a % 5))
	if [ "$fizz" -eq 0 ] && [ "$buzz" -eq 0 ]; then
		echo "FizzBuzz"
	elif [ "$fizz" ]; then
		echo "Fizz"
	elif [ "$buzz" ]; then
		echo "Buzz"
	else
		echo "$a"
	fi
done
