#!/usr/bin/env bash
# Prints bad luck on the 8 and 4 loop
i=1
while ((i <= 10)); do
	if ((i == 8)); then
		echo "good luck"
	elif ((i == 4)); then
		echo "bad luck"
	else
		echo "Best School"
	fi
	((i++))
done
